include(CheckIPOSupported)

function(neo_enable_lto target)
    if(NOT CMAKE_BUILD_TYPE STREQUAL "Debug")
        if(NOT ${CMAKE_SYSTEM_NAME} STREQUAL "Darwin")
            check_ipo_supported(RESULT LTO_SUPPORTED OUTPUT LTO_ERROR)
            if(LTO_SUPPORTED)
                message(STATUS "Enabling IPO for target ${target}")
                target_compile_options(${target} PRIVATE -flto)
                target_link_options(${target} PRIVATE -flto)
                set_target_properties(${target} PROPERTIES INTERPROCEDURAL_OPTIMIZATION TRUE)
            else()
                message(WARNING "IPO is not supported for target ${target}: ${LTO_ERROR}")
            endif()
        else()
            message(STATUS "Skipping IPO for target ${target}")
        endif()
    else()
        message(STATUS "Skipping IPO for target ${target} in Debug build type")
    endif()
endfunction()
