include(NeoTestBuildType)
include(NeoTestCompilerOptions)
include(NeoTestClangTidy)
include(NeoTestClangFormat)
include(NeoTestLinkTimeOptimization)
include(NeoTestSanitizers)
include(NeoTestDocumentation)
include(NeoTestCodeCoverage)
